"""Offline Cypher-script GraphStore — the default store implementation.

Mirrors hazop-ai's s2_pml schema (ADR-0001): every terminal becomes
(:PlantItem:<Type> {tag, name, equipment_type, detection_confidence, ...})
with `tag` unique, and connections split by direction evidence:

  known    -> (source)-[:FLOWS_TO {direction_sources, line_numbers}]->(target)
              the relationship direction IS the verified flow direction
  other    -> (a)-[:CONNECTED_TO {direction, ...}]->(b)
              drawing order, NOT flow — treat as undirected in queries

A "known" direction without an evidence source is a contract violation and
raises — FLOWS_TO never appears without direction_sources.
"""

from __future__ import annotations

import json
from pathlib import Path

# equipment_type -> extra node label (PascalCase); single words capitalize
_MULTIWORD_LABEL = {
    "check_valve": "CheckValve",
    "relief_valve": "ReliefValve",
    "control_valve": "ControlValve",
    "heat_exchanger": "HeatExchanger",
}

# attribute keys renamed to avoid clashing with Neo4j concepts
_RENAME = {"labels": "opc_labels"}

CONSTRAINT = ("CREATE CONSTRAINT plant_item_tag IF NOT EXISTS "
              "FOR (n:PlantItem) REQUIRE n.tag IS UNIQUE")


def _label(equipment_type: str) -> str:
    return _MULTIWORD_LABEL.get(equipment_type, equipment_type.capitalize())


def _lit(value) -> str:
    """A Cypher literal. JSON is valid Cypher for strings, numbers,
    booleans and flat lists — which is all the assembler emits."""
    return json.dumps(value, ensure_ascii=False)


def _map(props: dict) -> str:
    """A Cypher map literal; keys are known-safe identifiers."""
    return "{" + ", ".join(f"{k}: {_lit(v)}" for k, v in props.items()) + "}"


def _node_props(node: dict) -> dict:
    props = {
        "tag": node["tag"],
        "name": node["name"],
        "equipment_type": node["equipment_type"],
        "detection_confidence": node["detection_confidence"],
    }
    for key, value in node.get("attributes", {}).items():
        if value not in (None, "", []):
            props[_RENAME.get(key, key)] = value
    return props


def _rel(edge: dict) -> tuple[str, dict]:
    attrs = edge.get("attributes", {})
    direction = attrs.get("direction", "unknown")
    props = {}
    if attrs.get("line_numbers"):
        props["line_numbers"] = attrs["line_numbers"]
    if attrs.get("confidence") is not None:
        props["detection_confidence"] = attrs["confidence"]
    if attrs.get("provenance"):
        props["provenance"] = attrs["provenance"]
    if edge.get("line_tag"):
        props["line_tag"] = edge["line_tag"]
    if direction == "known":
        if not attrs.get("direction_sources"):
            raise ValueError(
                f"edge {edge['source']} -> {edge['target']} claims a known "
                "direction but carries no direction_sources; FLOWS_TO is "
                "never emitted without an evidence source")
        return "FLOWS_TO", props | {
            "direction_sources": attrs["direction_sources"]}
    props["direction"] = direction  # "unknown" (or "conflict")
    if attrs.get("direction_conflicts"):
        props["direction_conflicts"] = attrs["direction_conflicts"]
    if attrs.get("direction_note"):
        props["direction_note"] = attrs["direction_note"]
    return "CONNECTED_TO", props


def to_cypher_statements(graph: dict) -> list[str]:
    """The equipment-level graph as individual Cypher statements, without
    terminating semicolons — the single source both the offline script and
    the live Neo4j loader (ticket 09) execute, so asserting s2_pml
    conformance on the script covers live loads too. Idempotent: the
    constraint is IF NOT EXISTS and everything else MERGEs on the unique
    tag, so re-running a load creates nothing new."""
    statements = [CONSTRAINT]
    for node in graph["nodes"]:
        props = _node_props(node)
        statements.append(
            f"MERGE (n:PlantItem {{tag: {_lit(props['tag'])}}}) "
            f"SET n:{_label(node['equipment_type'])}, n += {_map(props)}")
    for edge in graph["edges"]:
        rtype, props = _rel(edge)
        set_clause = f" SET r += {_map(props)}" if props else ""
        statements.append(
            f"MATCH (a:PlantItem {{tag: {_lit(edge['source'])}}}), "
            f"(b:PlantItem {{tag: {_lit(edge['target'])}}}) "
            f"MERGE (a)-[r:{rtype}]->(b){set_clause}")
    return statements


def to_cypher(graph: dict) -> str:
    """Full idempotent Cypher script for the equipment-level graph
    (constraint, nodes, relationships). Safe to run repeatedly."""
    lines = [
        "// pidgraph plant graph — generated by pidgraph.cypher_store",
        "// FLOWS_TO = verified flow direction; CONNECTED_TO = drawing "
        "order only",
    ]
    lines += [statement + ";" for statement in to_cypher_statements(graph)]
    return "\n".join(lines) + "\n"


class CypherScriptGraphStore:
    """Default GraphStore: writes an operator-inspectable Cypher script.
    A run needs no live database to be useful."""

    def store(self, graph: dict, out_dir: Path | None = None) -> dict:
        script = to_cypher(graph)
        path = None
        if out_dir is not None:
            out_dir = Path(out_dir)
            out_dir.mkdir(parents=True, exist_ok=True)
            path = out_dir / "plant_graph.cypher"
            path.write_text(script, encoding="utf-8")
        return {
            "kind": "cypher-script",
            "script": script,
            "path": str(path) if path else None,
            "nodes": len(graph["nodes"]),
            "relationships": len(graph["edges"]),
        }
